### ISSUE TITLE
Issue when press 1 button redirect is not successfully .

### ISSUE THREAD

**Issue by nikhilnimje** [Nethram/callblaster#1]
Hello 
I installed callblaster in our server , we have asterisk version 1.4 , I configured outbound routing in our server , I set context test and extension 2323 ,when press 1 button , 

So when i upload the data and initiate calls , calls are going to customer side but when i press 1 button  error is coming in asterisk CLI 

Attempting call on Local/9857073529980@default for 333@callblaster:1 (Retry 1)
[Dec 17 15:55:26]     -- Executing [9857073529980@default:1] Dial("Local/9857073529980@default-1bb3,2", "SIP/917073529980@elision||To") in new stack
[Dec 17 15:55:26]     -- Called 917073529980@elision
[Dec 17 15:55:28]     -- SIP/elision-000000a9 is making progress passing it to Local/9857073529980@default-1bb3,2
[Dec 17 15:55:29] WARNING[3848]: chan_mgcp.c:4245 reload_config: Unable to get our IP address, MGCP disabled
[Dec 17 15:55:30]     -- SIP/elision-000000a9 answered Local/9857073529980@default-1bb3,2
[Dec 17 15:55:30]        > Channel Local/9857073529980@default-1bb3,1 was answered.
[Dec 17 15:55:30]     -- Executing [333@callblaster:1] AGI("Local/9857073529980@default-1bb3,1", "/var/www/html/callblaster/callblaster.php") in new stack
[Dec 17 15:55:30]     -- Launched AGI Script /var/www/html/callblaster/callblaster.php
[Dec 17 15:55:30]     -- <Local/9857073529980@default-1bb3,1> Playing '/var/www/html/callblaster/audio/guj_ivr' (language 'en')
[Dec 17 15:55:31]     -- Executing [h@default:1] DeadAGI("Local/9857073529980@default-1bb3,2", "agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----5-----1") in new stack
[Dec 17 15:55:31] ERROR[560]: utils.c:967 ast_carefulwrite: write() returned error: Connection refused
[Dec 17 15:55:31] WARNING[560]: res_agi.c:238 launch_netscript: Connect to 'agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----5-----1' failed: Connection refused
[Dec 17 15:55:31]   == Spawn extension (default, 9857073529980, 1) exited non-zero on 'Local/9857073529980@default-1bb3,2'
[Dec 17 15:55:31] NOTICE[559]: rtp.c:849 process_rfc3389: Comfort noise support incomplete in Asterisk (RFC 3389). Please turn off on client if possible. Client IP: 66.85.129.66
[Dec 17 15:55:35]     -- AGI Script Executing Application: (Goto) Options: (2323)
[Dec 17 15:55:35]     -- Goto (callblaster,333,2323)
[Dec 17 15:55:35]     -- AGI Script /var/www/html/callblaster/callblaster.php completed, returning 0
[Dec 17 15:55:35]   == Auto fallthrough, channel 'SIP/elision-000000a9' status is 'UNKNOWN'
[Dec 17 15:55:35] NOTICE[559]: pbx_spool.c:370 attempt_thread: Call completed to Local/9857073529980@default
[cli.txt](https://github.com/Nethram/callblaster/files/65274/cli.txt)

**Comment by Nethram** [comment]
It appears that you have not created the context for callblaster. Please follow the instructions. Here is the section that describes creating the callblaster context.

If FreePbx is installed in your server , you can create callblaster context in file extensions_custom.conf . Open extensions_custom.conf located in /etc/asterisk in a text editor and add following lines at the end of file.

;callblaster context

[callblaster]
exten => 333,1,AGI(/var/www/.....path to..../callblaster.php)

**Comment by nikhilnimje** [comment]
Nethram,

I already created a context for callblaster , and I didn’t installed freePBX

[callblaster]

exten => 333,1,AGI(/var/www/html/callblaster/callblaster.php)

exten => 333,n,Hangup()

See below CLI logs for your information.

(Goto) Options: (test,2323,1) it shows as priority for Goto(callblaster,333, (test,2323,1))

That’s y 

Priority 'test,2323,1' must be a number > 0, or valid label 

This error comes.

Please check and give me dialplan for asterisk 1.4 version.

[Dec 17 17:18:20]     -- Attempting call on Local/9857073529980@default for 333@callblaster:1 (Retry 1)

[Dec 17 17:18:20]     -- Executing [9857073529980@default:1] Dial("Local/9857073529980@default-0759,2", "SIP/917073529980@elision||To") in new stack

[Dec 17 17:18:20]     -- Called 917073529980@elision

[Dec 17 17:18:21]     -- SIP/elision-000000b1 is making progress passing it to Local/9857073529980@default-0759,2

[Dec 17 17:18:24]     -- SIP/elision-000000b1 answered Local/9857073529980@default-0759,2

[Dec 17 17:18:24]        > Channel Local/9857073529980@default-0759,1 was answered.

[Dec 17 17:18:24]     -- Executing [333@callblaster:1] AGI("Local/9857073529980@default-0759,1", "/var/www/html/callblaster/callblaster.php") in new stack

[Dec 17 17:18:24]     -- Launched AGI Script /var/www/html/callblaster/callblaster.php

[Dec 17 17:18:24]     -- <Local/9857073529980@default-0759,1> Playing '/var/www/html/callblaster/audio/guj_ivr' (language 'en')

[Dec 17 17:18:25]     -- Executing [h@default:1] DeadAGI("Local/9857073529980@default-0759,2", "agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----5-----1") in new stack

[Dec 17 17:18:25] ERROR[2825]: utils.c:967 ast_carefulwrite: write() returned error: Connection refused

[Dec 17 17:18:25] WARNING[2825]: res_agi.c:238 launch_netscript: Connect to 'agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----5-----1' failed: Connection refused

[Dec 17 17:18:25]   == Spawn extension (default, 9857073529980, 1) exited non-zero on 'Local/9857073529980@default-0759,2'

[Dec 17 17:18:25] NOTICE[2824]: rtp.c:849 process_rfc3389: Comfort noise support incomplete in Asterisk (RFC 3389). Please turn off on client if possible. Client IP: 66.85.129.66

[Dec 17 17:18:29]     -- AGI Script Executing Application: (Goto) Options: (test,2323,1)

[Dec 17 17:18:29] NOTICE[2824]: pbx.c:1917 pbx_extension_helper: No such label 'test,2323,1' in extension '333' in context 'callblaster'

[Dec 17 17:18:29] WARNING[2824]: pbx.c:6532 ast_parseable_goto: Priority 'test,2323,1' must be a number > 0, or valid label

[Dec 17 17:18:29]     -- AGI Script /var/www/html/callblaster/callblaster.php completed, returning 0

[Dec 17 17:18:29]     -- Executing [333@callblaster:2] Hangup("SIP/elision-000000b1", "") in new stack

[Dec 17 17:18:29]   == Spawn extension (callblaster, 333, 2) exited non-zero on 'SIP/elision-000000b1'

[Dec 17 17:18:29] NOTICE[2824]: pbx_spool.c:370 attempt_thread: Call completed to Local/9857073529980@default

**Comment by Nethram** [comment]
Suggest that you upgrade to a supported version of asterisk. 1.4 is an old version, and asterisk 1.4 has been end of life since 2012.

https://wiki.asterisk.org/wiki/display/AST/Asterisk+Versions

**Comment by nikhilnimje** [comment]
​
Nethram,

I already created a context for callblaster , and I didn’t installed freePBX

[callblaster]

exten => 333,1,AGI(/var/www/html/callblaster/callblaster.php)

exten => 333,n,Hangup()

See below CLI logs for your information.

(Goto) Options: (test,2323,1) it shows as priority for Goto(callblaster,333, (test,2323,1))

That’s y

Priority 'test,2323,1' must be a number > 0, or valid label

This error comes.

Please check and give me dialplan for asterisk 1.4 version.

[Dec 17 17:18:20]     -- Attempting call on Local/9857073529980@default for 333@callblaster:1 (Retry 1)

[Dec 17 17:18:20]     -- Executing [9857073529980@default:1] Dial("Local/9857073529980@default-0759,2", "SIP/917073529980@elision||To") in new stack

[Dec 17 17:18:20]     -- Called 917073529980@elision

[Dec 17 17:18:21]     -- SIP/elision-000000b1 is making progress passing it to Local/9857073529980@default-0759,2

[Dec 17 17:18:24]     -- SIP/elision-000000b1 answered Local/9857073529980@default-0759,2

[Dec 17 17:18:24]        > Channel Local/9857073529980@default-0759,1 was answered.

[Dec 17 17:18:24]     -- Executing [333@callblaster:1] AGI("Local/9857073529980@default-0759,1", "/var/www/html/callblaster/callblaster.php") in new stack

[Dec 17 17:18:24]     -- Launched AGI Script /var/www/html/callblaster/callblaster.php

[Dec 17 17:18:24]     -- <Local/9857073529980@default-0759,1> Playing '/var/www/html/callblaster/audio/guj_ivr' (language 'en')

[Dec 17 17:18:25]     -- Executing [h@default:1] DeadAGI("Local/9857073529980@default-0759,2", "agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----5-----1") in new stack

[Dec 17 17:18:25] ERROR[2825]: utils.c:967 ast_carefulwrite: write() returned error: Connection refused

[Dec 17 17:18:25] WARNING[2825]: res_agi.c:238 launch_netscript: Connect to 'agi://127.0.0.1:4577/call_log--HVcauses--PRI-----NODEBUG-----16-----ANSWER-----5-----1' failed: Connection refused

[Dec 17 17:18:25]   == Spawn extension (default, 9857073529980, 1) exited non-zero on 'Local/9857073529980@default-0759,2'

[Dec 17 17:18:25] NOTICE[2824]: rtp.c:849 process_rfc3389: Comfort noise support incomplete in Asterisk (RFC 3389). Please turn off on client if possible. Client IP: 66.85.129.66

[Dec 17 17:18:29]     -- AGI Script Executing Application: (Goto) Options: (test,2323,1)

[Dec 17 17:18:29] NOTICE[2824]: pbx.c:1917 pbx_extension_helper: No such label 'test,2323,1' in extension '333' in context 'callblaster'

[Dec 17 17:18:29] WARNING[2824]: pbx.c:6532 ast_parseable_goto: Priority 'test,2323,1' must be a number > 0, or valid label

[Dec 17 17:18:29]     -- AGI Script /var/www/html/callblaster/callblaster.php completed, returning 0

[Dec 17 17:18:29]     -- Executing [333@callblaster:2] Hangup("SIP/elision-000000b1", "") in new stack

[Dec 17 17:18:29]   == Spawn extension (callblaster, 333, 2) exited non-zero on 'SIP/elision-000000b1'
[Dec 17 17:18:29] NOTICE[2824]: pbx_spool.c:370 attempt_thread: Call completed to Local/9857073529980@default
